version: '2'

services:

  ## --------------------------------------------
  ## | Web Server Php7 and required Extensions
  ## --------------------------------------------
  poirot_web-server:
    # not accessible from host
    #ports:
    #- "8000:80"
    # environment:
      ## force /pap/ as a prefix to all routes
      # - PT_BASEURL=/pap
    networks:
      - poirot-network
      - network-front-proxy

  ## --------------------------------------------
  ## | Data Base Master Mongo Server
  ## --------------------------------------------
  # (!) poirot db configuration set to connect to it's host name
  db-master-mongo:
    networks:
      - poirot-network

  ## --------------------------------------------
  ## | Backup Data
  ## --------------------------------------------
  poirot_admin:
    networks:
      - poirot-network

  ## --------------------------------------------
  ## | Mongo Db Administration
  ## --------------------------------------------
  poirot_admin-mongo:
    ### access rockmongo with port binding
    ports:
      - "8081:8081"
    networks:
      - poirot-network
      - network-front-proxy

networks:
  poirot-network:
  network-front-proxy:
    external:
      name: frontproxy_front-network
##              ^             ^
##       name of project    network created inside that project
