<?php
/**
 * @var array       $_self          [ "validation_code"=>(string) ]
 * @var boolean     $is_validated   Is Verification Complete? (All Verification Items Is Valid).
 * @var array       $verifications [ ["email"=>(bool)], ["mobile"=>(bool)] ]
 * @var string|null $token         Token that lets user directly login if assert with session value
 *
 * @var \Module\Foundation\HttpSapi\ViewModelRenderer $this
 */

$this->htmlHeadTitle('Validate Your Identifiers');


$this->htmlScript()
    ->attachFile($this->path('app-assets').'/js/pages/verification.js')
    ->attachFile($this->path('app-assets').'/js/pages/verification_resend.js')
;
?>
<div class="login_page_wrapper">
    <div class="md-card" id="login_card">
        <div class="md-card-content large-padding" id="verification_form">
            <h2 class="heading_a uk-margin-large-bottom font-is">اهراز هویت</h2>
            <form action="<?php echo $this->url() ?>" method="POST" novalidate>

                <?php if (isset($verifications['email'])) { ?>
                <div class="uk-form-row verification-status verification-email <?php echo ($verifications['email']['is_validated']) ? 'verificate' : '' ?>">
                    <div class="verification-icon">
                        <i class="material-icons pending">radio_button_unchecked</i>
                        <i class="material-icons active">done</i>
                    </div>
                    <div class="verification-text">
                        <p class="pending">ایمیل شما در حال حاضر اهراز هویت نشده است.</p>
                        <p class="active">حساب کاربری شما اهراز هویت شد.</p>
                        <p class="hint">ایمیل اهراز هویت به آدرس الکترونیکی شما ارسال شد، با تایید ایمیل مراحل ثبت نام را کامل کنید.</p>

                        <p class="pending dir-ltr"><?php echo $verifications['email']['truncated']; ?></p>
                        <a href="<?php echo $this->url('main/oauth/recover/validate_resend', [
                                'validation_code' => $_self['validation_code'],
                                'identifier_type' => 'email',
                            ]
                        ) ?>" onclick="return handleResend(this);" class="resend-link"><i class="material-icons">repeat</i> ارسال مجدد</a>
                    </div>

                    <br/>
                    <br/>
                    <br/>

                    <div class="uk-form-row verificate-code">
                        <div class="parsley-row">
                            <input style="display: none" class="md-input font-is" type="text" name="email_code" placeholder="کد تایید" required/>
                        </div>
                    </div>

                </div>
                <?php } ?>

                <?php if (isset($verifications['mobile'])) { ?>
                <div class="uk-grid-divider"></div>
                <div class="uk-form-row verification-status verification-mobile <?php echo ($verifications['mobile']['is_validated']) ? 'verificate' : '' ?>">
                    <div class="verification-icon">
                        <i class="material-icons pending">radio_button_unchecked</i>
                        <i class="material-icons active">done</i>
                    </div>
                    <div class="verification-text">
                        <p class="pending">تلفن شما در حال حاضر تایید نشده است.</p>
                        <p class="active">تلفن همراه شما تایید شد.</p>
                        <p class="hint">برای اعتبارسنجی تلفن همراه خود کد تایید ارسالی  را در کادر زیر وارد کنید.</p>

                        <p class="pending dir-ltr"><?php echo $verifications['mobile']['truncated']; ?></p>
                        <a href="<?php echo $this->url('main/oauth/recover/validate_resend', [
                                'validation_code' => $_self['validation_code'],
                                'identifier_type' => 'mobile',
                            ]
                        ) ?>" onclick="return handleResend(this);" class="resend-link"><i class="material-icons">repeat</i> ارسال مجدد</a>
                    </div>
                </div>

                <div class="uk-form-row verificate-code">
                    <div class="parsley-row">
                        <input style="display: none" class="md-input font-is" type="text" name="mobile_code" placeholder="کد تایید" required/>
                    </div>
                </div>

                <?php } ?>

                <input type="hidden" name="login" value="login" />
                <div class="uk-margin-medium-top">
                    <button <?php if (!$is_validated) { ?> disabled="disabled" <?php } ?> type="submit" class="md-btn md-btn-primary md-btn-block font-is">ورود</button>
                </div>

            </form>

        </div>
    </div>
</div>
