<?php
/** @var \Module\Foundation\HttpSapi\ViewModelRenderer $this */
?>
<div class="error_page_header">
    <div class="uk-width-8-10 uk-container-center">خطای 404!</div>
</div>
<div class="error_page_content">
    <div class="uk-width-8-10 uk-container-center">
        <p class="heading_b font-is">صفحه ی مورد نظر پیدا نشد!</p>
        <p class="uk-text-large">آدرس صفحه ی مورد نظر در سرور وجود ندارد!</p>
        <a href="<?php echo $this->url('main/home') ?>">GO BACK TO THE HOMEPAGE</a>
    </div>
</div>