<?php
/**
 * @var \Module\Foundation\HttpSapi\ViewModelRenderer $this
 * @var array $client
 * @var array $scopes
 */

// TODO how to set this as final theme or change template (blank)
$this->htmlHeadTitle('Grant Authorize to Continue');
?>

<section id="error" class="container">
    <div class="jumbotron">
        <form action="" method="post">
            <h3><?php echo $client['name']; ?></h3>
            <h5><?php echo $client['description']; ?></h5>
            <p> Want to access <b><?php echo implode(', ', $scopes); ?></b> </p>

            <button type="submit" name="allow_access" class="btn btn-sm btn-success">Allow Access</button>
            <button type="submit" name="deny_access"  class="btn btn-sm btn-danger">Deny</button>
        </form>
    </div>
</section>
