<?php
/**
 * @var \Module\Foundation\HttpSapi\ViewModelRenderer $this
 */
use Module\OAuth2\Actions\User\LoginPage;

$this->htmlHeadTitle('Login To Continue');

$this->htmlScript()
    ->attachFile($this->path('app-assets').'/js/pages/login.js')
    ->attachFile($this->path().'/js/pages/common.js')
;

if ($this->flashMessage(LoginPage::FLASH_MESSAGE_ID)->hasMessages())
    echo $this->view( 'partial/flashMessage', $this->flashMessage(LoginPage::FLASH_MESSAGE_ID)->fetchMessages() );

?>
<div class="login_page_wrapper">
    <div class="md-card" id="login_card">
        <div class="md-card-content large-padding" id="login_form">
            <form action="<?php echo $this->url(null, null, true) ?>" method="post" novalidate>
                <div class="uk-form-row">
                    <div class="parsley-row">
                        <label for="login_username">نام کاربری</label>
                        <input class="md-input font-is" type="text" id="login_username" name="username" minlength="5" maxlength="32" required/>
                    </div>
                </div>
                <div class="uk-form-row">
                    <div class="parsley-row">
                        <label for="login_password">کلمه عبور</label>
                        <input class="md-input font-is" type="password" id="login_password" name="password" minlength="6" maxlength="32" autocomplete="off"  required/>
                    </div>
                </div>
                <div class="uk-margin-medium-top">
                    <button type="submit" class="md-btn md-btn-primary md-btn-block md-btn-large font-is">ورود</button>
                </div>
                <div class="uk-margin-top uk-margin-bottom">
                    <br/>
                    <a href="<?php echo $this->url('main/oauth/recover/signin_recognize', null, true); ?>" class="uk-float-right font-size-small">نمیتوانم وارد شوم، دیگر راههای ورود!</a>
                    <!--<span class="icheck-inline uk-margin-remove">
                            <input type="checkbox" name="login_page_stay_signed" id="login_page_stay_signed" data-md-icheck />
                            <label for="login_page_stay_signed" class="inline-label font-size-small">مرا به خاطر بسپار</label>
                        </span>-->
                </div>
            </form>
        </div>

    </div>
    <div class="uk-margin-top uk-text-center">
        <a href="<?php echo $this->url('main/oauth/register', null, true) ?>">ثبت نام</a>
    </div>
</div>
