<?php
/**
 * @var \Module\Foundation\HttpSapi\ViewModelRenderer $this
 * @var array                                         $user
 */
$this->htmlHeadTitle('Alternate Login Issues');

$this->htmlScript()
    ->attachFile($this->path('app-assets').'/js/pages/common.js')
;
?>
<div class="login_page_wrapper">
    <div class="md-card" id="login_card">
        <div class="md-card-content large-padding" id="login_form">
                <div class="uk-form-row" id="recognizeImages">
                    <img src="<?php echo $this->path('app-assets').'/img/user.png' ?>">
                    <p>کاربر گرامی، خوش آمدید ....</p>
                </div>
                <?php
                    $url = $this->url('main/oauth/logout', null, true);
                ?>
                <a href="<?php echo $url ?>" id="backStep" class="uk-position-top-right uk-close uk-margin-right uk-margin-top"></a>
        </div>

    </div>
</div>
