<?php
/**
 * @var \Module\Foundation\HttpSapi\ViewModelRenderer $this
 * @var string                                        $url_next_challenge
 * @var string                                        $mobile_truncate
 */
$this->htmlHeadTitle('Alternate Login Issues');

$this->htmlScript()
    ->attachFile($this->path('app-assets').'/js/pages/common.js')
;
?>
<div class="login_page_wrapper">
    <div class="md-card" id="login_card">
        <div class="md-card-content large-padding" id="login_form">
            <?php
            $url = $this->url(null, null, true);
            // prepend to achieve delete u params if has
            $url = \Poirot\Psr7\modifyUri($url->uri(), ['query' => ['u' => null, 'a'=>'start'] ], \Poirot\Psr7\URI_PREPEND);
            ?>
            <form action="<?php echo $url ?>" method="post" novalidate>
                <div class="uk-form-row" id="recognizeImages">
                    <img src="<?php echo $this->path('app-assets').'/img/sms.png' ?>">
                    <p class="info">
                        <span>ارسال پیامک حاوی کد شناسایی به شماره</span>
                        <span class="ltr"><?=$mobile_truncate?></span>
                    </p>
                </div>
                <div class="uk-margin-medium-top">
                    <button type="submit" class="md-btn md-btn-primary md-btn-block md-btn-large font-is">شروع</button>
                </div>
                <?php
                $url = $this->url('main/oauth/recover/signin_recognize', null, true);
                // prepend to achieve delete u params if has
                $url = \Poirot\Psr7\modifyUri($url->uri(), ['query' => ['u' => null] ], \Poirot\Psr7\URI_PREPEND);
                ?>
                <a href="<?php echo $url ?>" id="backStep" class="uk-position-top-right uk-close uk-margin-right uk-margin-top"></a>
            </form>
        </div>
    </div>
    <div class="md-card" id="next-step">
        <div class="md-card-content large-padding" id="next-step-content">
            <a href="<?php echo $url_next_challenge; ?>">بعدی</a>
        </div>
    </div>
</div>
