<?php
/** @var \Module\Foundation\HttpSapi\ViewModelRenderer $this */
?>
<!doctype html>
<!--[if lte IE 9]>
<html class="lte-ie9" lang="en" dir="rtl">
<![endif]-->
<!--[if gt IE 9]><!-->
<html lang="en" dir="rtl">
<!--<![endif]-->
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="initial-scale=1.0,maximum-scale=1.0,user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="msapplication-tap-highlight" content="no"/>

    <?php echo $this->htmlHeadTitle('Account Server') ?>

    <?php $this->path('app-assets') ## set app-assets as last invoked path and continue ...  ?>

    <link rel="stylesheet" media="all" href="<?php echo $this->path() ?>/fonts/IranSans/iransans.css"/>
    <link rel="stylesheet" media="all" href="<?php echo $this->path() ?>/css/uikit.rtl.css"/>
    <link rel="stylesheet" media="all" href="<?php echo $this->path() ?>/css/error_page.min.css"/>
    <link rel="stylesheet" media="all" href="<?php echo $this->path() ?>/css/pages/error.css"/>
</head>
<body class="error_page">
    <?php echo $content; ?>
</body>
</html>